<a href="https://colab.research.google.com/github/yohei0408/kikagaku/blob/main/20240930_%E3%83%87%E3%83%BC%E3%82%BF%E5%89%8D%E5%87%A6%E7%BD%AE%E5%9F%BA%E7%A4%8E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/lego.csv')
df.head()

,ages,list_price,num_reviews,piece_count,review_difficulty,star_rating,country
0,9-14,104.9078,4.0,746.0,Easy,4.3,DE
1,4-99,6.9860,3.0,60.0,Easy,4.7,GB
2,6-12,85.3878,5.0,575.0,Average,5.0,IE
3,9-14,146.3878,15.0,825.0,Average,4.7,BE
4,10+,42.6878,3.0,1.0,Average,5.0,BE

In [3]:
df.shape

(7142, 7)

In [4]:
df.duplicated(keep=False)

0       False
1       False
2       False
3       False
4       False
        ...
7137    False
7138    False
7139    False
7140    False
7141    False
Length: 7142, dtype: bool

In [6]:
df.duplicated(keep=False).value_counts()

False    6282
True      860
Name: count, dtype: int64

In [7]:
df.isnull().sum()

ages                  18
list_price             0
num_reviews            0
piece_count            0
review_difficulty      0
star_rating          405
country              255
dtype: int64

In [8]:
df.describe()

        list_price  num_reviews  piece_count  star_rating
count  7142.000000  7142.000000  7142.000000  6737.000000
mean     71.323455    17.283114   557.576869     4.504735
std      98.936980    36.418939   875.223553     0.517889
min       2.272400     1.000000     1.000000     1.800000
25%      20.986000     3.000000   115.000000     4.300000
50%      36.587800     6.000000   257.000000     4.600000
75%      79.990000    14.000000   603.000000     4.900000
max    1064.992900   367.000000  7541.000000     5.000000

In [9]:
df = df.fillna({'star_rating':df['star_rating'].median()})

In [10]:
df.isnull().sum()

ages                  18
list_price             0
num_reviews            0
piece_count            0
review_difficulty      0
star_rating            0
country              255
dtype: int64

In [11]:
df.describe()

        list_price  num_reviews  piece_count  star_rating
count  7142.000000  7142.000000  7142.000000  7142.000000
mean     71.323455    17.283114   557.576869     4.510137
std      98.936980    36.418939   875.223553     0.503472
min       2.272400     1.000000     1.000000     1.800000
25%      20.986000     3.000000   115.000000     4.300000
50%      36.587800     6.000000   257.000000     4.600000
75%      79.990000    14.000000   603.000000     4.900000
max    1064.992900   367.000000  7541.000000     5.000000

In [12]:
df.shape

(7142, 7)

In [13]:
df = pd.get_dummies(df, columns=['country'], drop_first=True)
df.shape

(7142, 26)